#
###################################
# Site wide configuration
####################################
#
title: Aditya Kushwaha
email: contact.kushwaha@gmail.com
description: Product Developer - Former Lead Android Developer at Zomato
url: # the base hostname & protocol for your site


#
###################################
# Jekyll configuration
####################################
#
timezone:          Europe/Paris
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: Aditya Kushwaha
  avatar: leonids-logo.png
  job: "A jekyll theme"
  bio: "Product Developer - Former Lead Android Developer at Zomato"
  email: contact.kushwaha@gmail.com
  disqus-shortname:
  twitter: kushwaha_aditya
  facebook: #username
  google:
    plus: #username
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: adityaKushwaha
  gitlab: #username
  stackoverflow: 1724697/kushwaha
  linkedin: adityakushwaha
  skype: aditya.kushwaha
  xing: #username
  instagram: instalitre
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  500px: #username
  codepen: #username
